version: '3.1'

services:
  mysql:
    container_name: check
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      TZ: UTC
    ports:
      - 3306:3306